// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.RSStoJSON
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("source")]
        public string Source { get; set; }

        [JsonProperty("articles")]
        public long Articles { get; set; }

        [JsonProperty("maxReached")]
        public bool MaxReached { get; set; }

        [JsonProperty("feed")]
        public Feed[] Feed { get; set; }
    }

    public partial class Feed
    {
        [JsonProperty("website")]
        public Website Website { get; set; }

        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("pubDate")]
        public string PubDate { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }

        [JsonProperty("link")]
        public Uri Link { get; set; }
    }

    public enum Website { Nasa };
}
